name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  schedule:
    # Runs once every 7 days (Sunday at 03:00 UTC)
    - cron: '0 3 * * 0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------- iHD (modern Intel) --------
      - name: Build iHD VAAPI image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/peertube-vaapi:production-trixie-ihd .

      - name: Push iHD VAAPI image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/peertube-vaapi:production-trixie-ihd

      # -------- i965 (Intel CPU (generation 7 and older)) --------
      - name: Build i965 VAAPI image
        run: |
          docker build \
            --build-arg VAAPI_DRIVER=i965-va-driver-shaders \
            -t ghcr.io/${{ github.repository_owner }}/peertube-vaapi:production-trixie-i965 .

      - name: Push i965 VAAPI image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/peertube-vaapi:production-trixie-i965
